<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-27F8N879" failures="2" tests="3" name="Test" time="0.081" errors="0" timestamp="2021-02-21T13:08:46 IST">
  <testcase classname="com.practice.integration.Pracauto.PraticeTest1" name="method1" time="0.017">
    <failure type="java.lang.AssertionError" message="expected [4] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [4] but found [1]
at com.practice.integration.Pracauto.PraticeTest1.method1(PraticeTest1.java:15)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- method1 -->
  <testcase classname="com.practice.integration.Pracauto.PraticeTest1" name="method2" time="0.002"/>
  <testcase classname="com.practice.integration.Pracauto.PraticeTest1" name="method3" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [4] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [4] but found [1]
at com.practice.integration.Pracauto.PraticeTest1.method3(PraticeTest1.java:29)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- method3 -->
</testsuite> <!-- Test -->
